<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>CARBONCILLO</title>
  </head>
  <body>
    <h1>EL CARBONCILLO</h1>

    <table>

        <td width = "1000"><center>QUE ES EL OLEO??</center></td>

      <tr>
         <td><center><img src = "leonardo.jpg" width = "200" height="200" class = "pintor"></center></td>
      </tr>
      <tr><td>
        En su tratado técnico, Il libro dell'arte (El libro del arte), de principios del siglo XV, Cennino Cennini recomendaba atar un carboncillo de
        sauce a una caña para poder distanciarse de la superficie al pintar –en su época sobre tabla o al fresco
       y trazar así el dibujo preparatorio con el carboncillo en una mano y con una pluma de ave en la otra, para borrar el trazo si fuese necesario
      </td></tr>
  </body>
</html>
